#!/usr/bin/env python3
"""Extract the generated Unicode maps from src/md4x.c (HEAD reference) by
compiling a tiny C program that #includes the relevant array literals via the
exact same R()/S() macros, then prints the expanded unsigned arrays. We avoid
hand-retyping by letting the C preprocessor expand the ranges.
"""
import re, subprocess, sys, os

SRC = sys.argv[1] if len(sys.argv) > 1 else "/tmp/md4x-c-ref.c"
src = open(SRC).read()

def extract_array(name):
    # find: static const unsigned NAME[] = { ... };
    m = re.search(r'static const unsigned '+re.escape(name)+r'\[\]\s*=\s*\{(.*?)\};', src, re.S)
    if not m:
        raise SystemExit("not found: "+name)
    return m.group(1)

names = ["WHITESPACE_MAP","PUNCT_MAP","FOLD_MAP_1","FOLD_MAP_1_DATA",
         "FOLD_MAP_2","FOLD_MAP_2_DATA","FOLD_MAP_3","FOLD_MAP_3_DATA"]

# Build a C program: arrays that use R/S macros need them defined; DATA arrays are plain.
prog = ['#include <stdio.h>',
        '#define R(cp_min, cp_max)   ((cp_min) | 0x40000000), ((cp_max) | 0x80000000)',
        '#define S(cp)               (cp)']
for n in names:
    body = extract_array(n)
    prog.append(f'static const unsigned {n}[] = {{{body}}};')
prog.append('int main(void){')
for n in names:
    prog.append(f'  printf("{n}\\n");')
    prog.append(f'  for(unsigned i=0;i<sizeof({n})/sizeof({n}[0]);i++) printf("%u\\n", {n}[i]);')
    prog.append(f'  printf("END\\n");')
prog.append('  return 0;}')
open("/tmp/extract_tables.c","w").write("\n".join(prog))
subprocess.run(["zig","cc","-O2","/tmp/extract_tables.c","-o","/tmp/extract_tables"], check=True)
out = subprocess.run(["/tmp/extract_tables"], capture_output=True, text=True, check=True).stdout
# parse
arrays = {}
cur=None
for line in out.splitlines():
    if line in names:
        cur=line; arrays[cur]=[]
    elif line=="END":
        cur=None
    elif cur is not None:
        arrays[cur].append(int(line))

def fmt(vals):
    out=[]
    for i in range(0,len(vals),12):
        out.append("    "+", ".join(str(v) for v in vals[i:i+12])+",")
    return "\n".join(out)

L=[]
L.append("// AUTO-GENERATED by scripts/_gen-tables-zig.py from src/md4x.c — do not edit by hand.")
L.append("// Unicode classification maps (whitespace/punct/case-folding), expanded from the")
L.append("// R()/S() range-encoding macros via the C preprocessor for exact byte-parity.")
L.append("")
for n in names:
    L.append(f"pub const {n} = [_]c_uint{{")
    L.append(fmt(arrays[n]))
    L.append("};")
    L.append("")
open("src/unicode_tables.zig","w").write("\n".join(L))
print("Generated src/unicode_tables.zig")
for n in names:
    print(f"  {n}: {len(arrays[n])} entries")
