#!/usr/bin/env python3
"""Throwaway generator: parse src/entity.c ENTITY_MAP[] and emit src/entity.zig.

Produces a Zig module with:
  - extern struct ENTITY { name: [*:0]const u8, codepoints: [2]c_uint }
  - fn entity_lookup(name, name_size) ?*const ENTITY
mirroring the C bsearch over a sorted table with strncmp(key, ent, name_size).

NOTE: its input, src/entity.c, was deleted with the C ABI, so this script can no
longer be re-run. It is kept as the record of how src/entity.zig was produced.
When src/entity.zig must change, change BOTH in lockstep so they stay
consistent (that is how the Phase 4b de-extern of entity_lookup was applied).
"""
import re
import sys

SRC = sys.argv[1] if len(sys.argv) > 1 else "src/entity.c"
OUT = sys.argv[2] if len(sys.argv) > 2 else "src/entity.zig"

entry_re = re.compile(r'^\s*\{\s*"((?:[^"\\]|\\.)*)"\s*,\s*\{\s*(\d+)\s*,\s*(\d+)\s*\}\s*\}\s*,?\s*$')

entries = []
with open(SRC, "r", encoding="utf-8") as f:
    in_map = False
    for line in f:
        if "ENTITY_MAP[]" in line and "=" in line:
            in_map = True
            continue
        if in_map:
            if line.strip().startswith("};"):
                in_map = False
                continue
            m = entry_re.match(line)
            if not m:
                # skip blank / stray lines but error on unexpected content
                if line.strip() == "":
                    continue
                raise SystemExit(f"Unparsed line in ENTITY_MAP: {line!r}")
            name, cp0, cp1 = m.group(1), int(m.group(2)), int(m.group(3))
            entries.append((name, cp0, cp1))

if not entries:
    raise SystemExit("No entries parsed!")

# Zig string-literal escaping for names. Names are ASCII identifiers like &AElig;
def zig_str(s):
    out = []
    for ch in s:
        if ch == '"':
            out.append('\\"')
        elif ch == '\\':
            out.append('\\\\')
        else:
            out.append(ch)
    return '"' + ''.join(out) + '"'

lines = []
lines.append("// AUTO-GENERATED by scripts/_gen-entity-zig.py from src/entity.c — do not edit by hand.")
lines.append("//")
lines.append("// HTML entity lookup table (mirrors the C ENTITY_MAP[]). Imported directly by")
lines.append("// the parser and the renderers; see src/lib.zig.")
lines.append("")
lines.append("const std = @import(\"std\");")
lines.append("")
lines.append("/// Entity record: the name including '&' and ';', and 1-2 codepoints.")
lines.append("pub const ENTITY = extern struct {")
lines.append("    name: [*:0]const u8,")
lines.append("    codepoints: [2]c_uint,")
lines.append("};")
lines.append("")
lines.append(f"const ENTITY_MAP = [{len(entries)}]ENTITY{{")
for name, cp0, cp1 in entries:
    lines.append(f"    .{{ .name = {zig_str(name)}, .codepoints = .{{ {cp0}, {cp1} }} }},")
lines.append("};")
lines.append("")
lines.append("/// Mirrors entity_cmp: strncmp(key->name, ent->name, key->name_size).")
lines.append("/// Returns the C strncmp result semantics (sign only matters for bsearch).")
lines.append("fn entityCmp(key: []const u8, ent: *const ENTITY) c_int {")
lines.append("    const a = key;")
lines.append("    const b = ent.name;")
lines.append("    var i: usize = 0;")
lines.append("    while (i < a.len) : (i += 1) {")
lines.append("        const ca: u8 = a[i];")
lines.append("        const cb: u8 = b[i];")
lines.append("        if (ca != cb) {")
lines.append("            // strncmp compares as unsigned char.")
lines.append("            return @as(c_int, ca) - @as(c_int, cb);")
lines.append("        }")
lines.append("        if (cb == 0) return 0; // both equal and reached NUL")
lines.append("    }")
lines.append("    return 0;")
lines.append("}")
lines.append("")
lines.append("/// Look up a named HTML entity; returns null if unknown.")
lines.append("/// Replicates the C bsearch over the sorted ENTITY_MAP using entity_cmp.")
lines.append("pub fn entity_lookup(name: [*]const u8, name_size: usize) ?*const ENTITY {")
lines.append("    const key = name[0..name_size];")
lines.append("    var lo: usize = 0;")
lines.append("    var hi: usize = ENTITY_MAP.len;")
lines.append("    while (lo < hi) {")
lines.append("        const mid = lo + (hi - lo) / 2;")
lines.append("        const c = entityCmp(key, &ENTITY_MAP[mid]);")
lines.append("        if (c == 0) {")
lines.append("            return &ENTITY_MAP[mid];")
lines.append("        } else if (c < 0) {")
lines.append("            hi = mid;")
lines.append("        } else {")
lines.append("            lo = mid + 1;")
lines.append("        }")
lines.append("    }")
lines.append("    return null;")
lines.append("}")
lines.append("")

with open(OUT, "w", encoding="utf-8") as f:
    f.write("\n".join(lines))

print(f"Parsed {len(entries)} entries -> {OUT}")
